config/routes.rb
Rails.application.routes.draw do
  resources :challenges
  resources :tasks
  resource :example, constraints: -> { Rails.env.development? }
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  post "change_context", to: "sessions#change_context"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  post "sign_in", to: "sessions#create"

  post "become_teacher", to: "professors#become_teacher"
  resources :rooms
  get  "r/:code", to: "room_requests#new", as: :room_request
  get  "rooms/:id/select", to: "rooms#select", as: :select_room
  get  "room_request_success", to: "room_requests#success", as: :success_room_request

  resources :room_requests, only: [:new, :create]




















  get "home/index"

  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  root "home#index"
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id           :uuid             not null, primary key
#  code         :string           not null
#  name         :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  professor_id :uuid             not null
#
# Indexes
#
#  index_rooms_on_professor_id  (professor_id)
#
# Foreign Keys
#
#  fk_rails_...  (professor_id => professors.id)
#
class Room < ApplicationRecord
  belongs_to :professor
  has_many :room_requests
  has_many :students, -> { joins(:room_requests).where(room_requests: {accepted: true}) }, through: :room_requests

  validates :name, presence: true, length: { minimum: 3, maximum: 32}
  validates :code, presence: true, length: { minimum: 6, maximum: 6}
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
  before_action :ensure_professor, only: %i[ new edit update destroy ]

  skip_before_action :authenticate, only: %i[ new_request_entry ]

  def select
    if params[:destroy]
      Current.user.update!(selected_room_id: nil)
      redirect_to root_path
    else
      room = Room.find(params[:id])
      Current.user.update!(selected_room_id: room.id)
      redirect_to root_path
    end
  end

  def new_request_entry
    render Rooms::RequestView.new(room_request: nil)
    return
    # TODO move logic to model
    user = Current.user
    room = Room.find_by(code: params[:code])

    if user
      session[:request_entry] = nil
      room_request = RoomRequest.create!(student: Current.user.student, room: room)

      render Rooms::RequestView.new(room_request: room_request)
    else
      session[:request_entry] = params[:code]
      redirect_to sign_in_path
    end
  end

  # GET /rooms or /rooms.json
  def index
    if Current.user.professor?
      # TODO tenant
      @rooms = Room.all
    else
      @rooms = Current.user.student.rooms
    end
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @requests = @room.room_requests.where(accepted: false)
    @students = @room.students.eager_load(:user, :room_requests)
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)
    @room.professor = Current.user.professor
    @room.code = SecureRandom.alphanumeric(6)

    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_path, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy!

    respond_to do |format|
      format.html { redirect_to rooms_path, status: :see_other, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.expect(room: [ :name ])
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, class: "contents") do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :code %>
    <%= form.text_field :code, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :professor_id %>
    <%= form.text_field :professor_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Code:</strong>
    <%= room.code %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= room.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Professor:</strong>
    <%= room.professor_id %>
  </p>

</div>

app/views/rooms/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing room</h1>

  <%= render "form", room: @room %>

  <%= link_to "Show this room", @room, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to rooms", rooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/rooms/index.html.erb
<div class="flex justify-between items-center">
  <h1 class="text-4xl font-bold">Turmas</h1>
  <% if Current.user.professor? %>
    <%= link_to "Nova", new_room_path, class: "btn btn-primary" %>
  <% end %>
</div>

<div id="rooms" class="min-w-full">
  <% @rooms.each do |room| %>
    <%= render RoomCardComponent.new(room: room) %>
  <% end %>
</div>

app/views/rooms/new.html.erb
<%= render Rooms::Form.new(@room) %>

app/views/rooms/show.html.erb
<div class="flex justify-between items-center">
  <h1 class="text-4xl font-bold">Alunos</h1>
</div>

<% @requests.each do |room_request| %>
  <%= render RoomRequestCardComponent.new(room_request) %>
<% end %>


<% @students.each do |student| %>
  <%= render StudentCardComponent.new(student, @room) %>
<% end %>