config/routes.rb
Rails.application.routes.draw do
  resources :challenges
  resources :tasks
  resource :example, constraints: -> { Rails.env.development? }
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  post "change_context", to: "sessions#change_context"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  post "sign_in", to: "sessions#create"

  post "become_teacher", to: "professors#become_teacher"
  resources :rooms
  get  "r/:code", to: "room_requests#new", as: :room_request
  get  "rooms/:id/select", to: "rooms#select", as: :select_room
  get  "room_request_success", to: "room_requests#success", as: :success_room_request

  resources :room_requests, only: [:new, :create]




















  get "home/index"

  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  root "home#index"
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/challenge.rb
# == Schema Information
#
# Table name: challenges
#
#  id         :uuid             not null, primary key
#  difficulty :integer
#  problem    :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :uuid             not null
#
# Indexes
#
#  index_challenges_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Challenge < ApplicationRecord
  acts_as_tenant(:user)

  has_rich_text :problem

  enum :difficulty, [:easy, :itermediate, :hard], default: :easy

  validates :title, presence: true, length: { minimum: 6}
  validates :problem, presence: true, length: { minimum: 60}
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: %i[ show edit update destroy ]

  # GET /challenges or /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1 or /challenges/1.json
  def show
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges or /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: "Challenge was successfully created." }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1 or /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: "Challenge was successfully updated." }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1 or /challenges/1.json
  def destroy
    @challenge.destroy!

    respond_to do |format|
      format.html { redirect_to challenges_path, status: :see_other, notice: "Challenge was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def challenge_params
      params.expect(challenge: [ :step_id, :title, :problem, :difficulty ])
    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_challenge.html.erb
<div id="<%= dom_id challenge %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= challenge.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Problem:</strong>
    <div class="trix-content">
      <%= challenge.problem %>
    </div>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Difficulty:</strong>
    <%= challenge.difficulty %>
  </p>

</div>

app/views/challenges/_form.html.erb
<%= form_with(model: challenge, class: "contents") do |form| %>
  <% if challenge.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
        <% challenge.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :step_id %>
    <%= form.text_field :step_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :problem %>
    <%= form.textarea :problem, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :difficulty %>
    <%= form.select :difficulty, Challenge.difficulties, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<%= render Challenges::Form.new(@challenge) %>

app/views/challenges/index.html.erb
<div class="flex justify-between items-center">
  <h1 class="text-4xl font-bold">Desafios</h1>
    <%= link_to "Novo", new_challenge_path, class: "btn btn-primary" %>
</div>

<div id="rooms" class="min-w-full">
  <% @challenges.each do |challenge| %>
    <%= render ChallengeCardComponent.new(challenge) %>
  <% end %>
</div>

app/views/challenges/new.html.erb
<%= render Challenges::Form.new(@challenge) %>

app/views/challenges/show.html.erb
<div class="flex justify-between items-center">
  <h1 class="text-4xl font-bold">Dados desafio</h1>
  <div>
    <%= link_to "Voltar", challenges_path, class: "btn btn-secondary" %>
    <%= link_to "Deletar", @challenge, data: { "turbo-method": :delete, turbo_confirm: "Deseja deletar desafio?"}, class: "btn btn-error" %>
    <%= link_to "Editar", edit_challenge_path(@challenge), class: "btn btn-primary" %>
  </div>
</div>

<%= render @challenge %>